version: "3"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    command: flask run --debugger --host=0.0.0.0
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    depends_on:
      - redis

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  pgdata:
